login: &login
  adapter: mysql
  host: localhost
  reconnect: true
  encoding: utf8
  pool: 5

development:
  <<: *login
  username: root
  database: peladeiros_development
  password: root
production:
  development

test:
  <<: *login
  username: root
  database: peladeiros_test
  password: root
cucumber:
  test
